### ISSUE TITLE
How to use this date picker?

### ISSUE THREAD

**Issue by pratiksharma9** [jkuri/ng2-datepicker#55]
Hello all,

Please update **README** that how to use.

**Comment by connecttheworld** [comment]
Which version of Angular 2 are you trying to integrate with.  The official release or a RC version?  It makes a difference if your version of Angular 2 uses NgModules or not.

**Comment by cukingpro** [comment]
Hi 
I'm using Angular RC 5 and it uses ngModule
When I imported to the module. It said cannot find module ng2-datepicker

**Comment by connecttheworld** [comment]
@cukingpro If you look at the package.json, ng2-datepicker uses Angular RC.4, which doesn't use NgModule if I'm not mistaken.  Check out the comments from #49 .  

I think you need in the module where you are using the datepicker.

```
import {DatePicker} from 'ng2-datepicker/ng2-datepicker';

@NgModule({
  ...,
  declarations: [DatePicker, ...],
  ...
})
```

**Comment by jkuri** [comment]
That's right. This should work with Angular 2.0.0.

**Comment by 25ar** [comment]
Hello.
I use angular 2.0.0-rc.5. Can someone explain how to use this module?
In my app.mosule.ts I did:
import { DatePicker } from '../node_modules/ng2-datepicker/ng2-datepicker';
...
@NgModule({
  ...,
  declarations: [DatePicker, ...],
  ...
})

But after compilation I get error:
Error: SyntaxError: Unexpected token <
	    at Object.eval (http://10.10.17.179:8181/js/app.module.js:16:24)
	    at eval (http://10.10.17.179:8181/js/app.module.js:50:4)
	    at eval (http://10.10.17.179:8181/js/app.module.js:51:3)
	Evaluating http://10.10.17.179:8181/node_modules/ng2-datepicker/ng2-datepicker
	Evaluating http://10.10.17.179:8181/js/app.module.js
	Evaluating http://10.10.17.179:8181/js/main.js
	Error loading http://10.10.17.179:8181/js/main.js

**Comment by jkuri** [comment]
https://github.com/jkuri/ng2-datepicker/pull/62

**Comment by rrohitesh** [comment]
i am facing a issue in customizing the ng2-datepicker past dates back-ground color. As i see in the .css only current and selected dates selectors is there. There is no .css selector for the past dates. Does anybody know how we can change the color of background for past dates.
